"use strict";
const $=id=>document.getElementById(id);
let token="", state=null, currentPersona=null, currentProvider=null, timer=null;
const pageNames={overview:"总览",persona:"人设工作台",providers:"模型接口",generate:"生图工作台",active:"主动消息",history:"生成历史"};
try{token=sessionStorage.getItem("persona-studio-token")||"";}catch(_){ }
function text(id,value){$(id).textContent=value==null||value===""?"—":String(value)}
function esc(value){return String(value??"")}
function notice(message,error=false){const n=$("notice");n.hidden=!message;n.textContent=message;n.className=`notice${error?" error":""}`}
function login(message=""){token="";try{sessionStorage.removeItem("persona-studio-token")}catch(_){};$("login-error").hidden=!message;$("login-error").textContent=message;if(!$("login").open)$("login").showModal();$("status-label").textContent="等待登录";$("status-dot").className="dot"}
async function request(path,options={}){const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(options.headers||{})},cache:"no-store"});let data={};try{data=await response.json()}catch(_){}if(response.status===401){login(data.error||"令牌无效");throw new Error(data.error||"令牌无效")}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function setPage(page){document.querySelectorAll("[data-panel]").forEach(x=>x.hidden=x.dataset.panel!==page);document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));text("page-title",pageNames[page]||page)}
function fillPersona(p){currentPersona=p;["name","description","positive","negative","style"].forEach(key=>$("p-"+key).value=p[key==="name"?"name":key==="description"?"description":key==="positive"?"positive_prompt":key==="negative"?"negative_prompt":"style_prompt"]||"");const s=p.state||{};$("p-outfit").value=s.outfit||"";$("p-pose").value=s.pose||"";$("p-expression").value=s.expression||"";$("p-scene").value=s.scene||"";$("p-pool").value=(p.outfit_pool||[]).join("\n");renderPrompt(p)}
function renderPrompt(p){const s=p?.state||{};$("prompt-preview").textContent=`正面：${[p?.style_prompt,p?.positive_prompt,s.outfit,s.pose,s.expression,s.scene].filter(Boolean).join(", ")}\n\n负面：${p?.negative_prompt||""}`}
function renderPersonas(items){const box=$("persona-list");box.replaceChildren();for(const p of items){const row=document.createElement("div");row.className=`list-row ${p.id===currentPersona?.id?"active":""}`;row.innerHTML=`<span>${esc(p.name)} <small>${esc(p.id)}</small></span><button data-persona="${esc(p.id)}">编辑</button>`;box.append(row);row.querySelector("button").onclick=()=>fillPersona(p)}}
function renderProviders(items){const box=$("provider-list");box.replaceChildren();for(const p of items){const row=document.createElement("div");row.className=`list-row ${p.name===currentProvider?.name?"active":""}`;row.innerHTML=`<span>${esc(p.name)} <small>${esc(p.kind)} / ${esc(p.model||"未配置模型")}</small></span><button data-provider="${esc(p.name)}">编辑</button>`;box.append(row);row.querySelector("button").onclick=()=>fillProvider(p)}}
function fillProvider(p){currentProvider=p;$("v-name").value=p.name||"";$("v-kind").value=p.kind||"openai";$("v-endpoint").value=p.endpoint||"";$("v-model").value=p.model||"";$("v-key").value="";$("v-header").value=p.auth_header||"Authorization";$("v-prefix").value=p.auth_prefix??"Bearer ";$("v-edit").checked=Boolean(p.supports_image_edit);$("v-negative").checked=p.negative_prompt!==false}
function renderTargets(items){const box=$("target-list");box.replaceChildren();if(!items.length){box.textContent="暂无目标。请先在 QQ 私聊中与机器人产生一次消息。";return}for(const t of items){const row=document.createElement("div");row.className="list-row";row.innerHTML=`<span>${esc(t.sender_id||t.umo)} <small>${t.enabled?"已启用":"已停用"} · 未回复 ${t.unanswered||0} 次</small></span><span><button data-toggle="${esc(t.umo)}">${t.enabled?"停用":"启用"}</button> <button data-remove="${esc(t.umo)}">移除</button></span>`;box.append(row);row.querySelector("[data-toggle]").onclick=()=>targetAction({action:"toggle",umo:t.umo});row.querySelector("[data-remove]").onclick=()=>targetAction({action:"remove",umo:t.umo})}}
function renderHistory(items){const box=$("history-list");box.replaceChildren();if(!items.length){box.textContent="还没有生成记录。";return}for(const h of [...items].reverse()){const row=document.createElement("div");row.className="history-row";const image=h.image?`<img src="${esc(h.image)}" alt="生成结果">`:"<div></div>";row.innerHTML=`${image}<div><strong>${esc(h.caption||h.prompt||"未命名请求")}</strong><small>${esc(h.provider||"")} · ${h.ok?"成功":"失败"}</small><p>${esc(h.error||"")}</p></div><small>${new Date((h.at||0)*1000).toLocaleString("zh-CN")}</small>`;box.append(row)}}
function renderOverview(data){const p=data.persona||{};text("overview-name",p.name);text("overview-description",p.description);text("overview-provider",`模型 ${data.settings?.default_provider||"—"}`);text("overview-reference",`参考图 ${p.reference_enabled?"已开启":"未开启"}`);const s=p.state||{};text("overview-state",[s.outfit,s.pose,s.scene].filter(Boolean).join(" · ")||"未设置");text("overview-targets",(data.targets||[]).length);text("overview-history",(data.history||[]).length)}
async function load(){const [data,personas,providers,targets,history]=await Promise.all([request("/api/state"),request("/api/personas"),request("/api/providers"),request("/api/targets"),request("/api/history")]);state=data;renderOverview(data);renderPersonas(personas.items||[]);renderProviders(providers.items||[]);renderTargets(targets.items||[]);renderHistory(history.items||[]);if(!currentPersona&&personas.items?.length)fillPersona(personas.items[0]);if(!currentProvider&&providers.items?.length)fillProvider(providers.items[0]);$("status-label").textContent="控制台已连接";$("status-dot").className="dot online"}
async function targetAction(body){try{await request("/api/targets",{method:"POST",body:JSON.stringify(body)});await load()}catch(e){notice(e.message,true)}}
async function submitGenerate(input,output){$(output).textContent="生成中…";try{const result=await request("/api/generate",{method:"POST",body:JSON.stringify(input)});$(output).innerHTML=result.image?`<p>${esc(result.caption||"生成完成")}</p><img src="${esc(result.image)}" alt="生成结果">`:`<p>${esc(result.message||"生成完成")}</p>`;await load()}catch(e){$(output).textContent=e.message;notice(e.message,true)}}
document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>setPage(x.dataset.page));$("refresh").onclick=()=>load().catch(e=>notice(e.message,true));$("logout").onclick=()=>login();
$("login-form").onsubmit=async e=>{e.preventDefault();token=$("token").value.trim();try{await request("/api/state");try{sessionStorage.setItem("persona-studio-token",token)}catch(_){}$("login").close();await load()}catch(err){$("login-error").hidden=false;$("login-error").textContent=err.message}};
$("quick-form").onsubmit=e=>{e.preventDefault();const prompt=$("quick-input").value.trim();if(prompt)submitGenerate({text:prompt},"quick-result")};
$("save-persona").onclick=async()=>{const p={...(currentPersona||{}),id:currentPersona?.id||`persona-${Date.now()}`,name:$("p-name").value,description:$("p-description").value,positive_prompt:$("p-positive").value,negative_prompt:$("p-negative").value,style_prompt:$("p-style").value,state:{outfit:$("p-outfit").value,pose:$("p-pose").value,expression:$("p-expression").value,scene:$("p-scene").value},outfit_pool:$("p-pool").value.split(/\r?\n/).filter(Boolean)};try{await request("/api/personas",{method:"POST",body:JSON.stringify(p)});notice("人设已保存");await load()}catch(e){notice(e.message,true)}};
$("new-persona").onclick=()=>fillPersona({id:`persona-${Date.now()}`,name:"新的人设",state:{},outfit_pool:[]});$("reset-state").onclick=()=>{if(currentPersona)fillPersona({...currentPersona,state:{}})};
$("save-provider").onclick=async()=>{const p={name:$("v-name").value,kind:$("v-kind").value,endpoint:$("v-endpoint").value,model:$("v-model").value,api_key:$("v-key").value,auth_header:$("v-header").value,auth_prefix:$("v-prefix").value,supports_image_edit:$("v-edit").checked,negative_prompt:$("v-negative").checked};try{await request("/api/providers",{method:"POST",body:JSON.stringify(p)});notice("模型接口已保存");await load()}catch(e){notice(e.message,true)}};
$("new-provider").onclick=()=>fillProvider({name:`provider-${Date.now()}`,kind:"openai"});$("generate-button").onclick=()=>submitGenerate({text:$("g-prompt").value,mode:$("g-mode").value,provider:$("g-provider").value,width:Number($("g-width").value),height:Number($("g-height").value)},"generate-result");
$("save-active").onclick=async()=>{try{await request("/api/settings",{method:"POST",body:JSON.stringify({active:{enabled:$("a-enabled").checked,check_interval_sec:Number($("a-interval").value),min_gap_sec:Number($("a-gap").value),silence_after:Number($("a-silence").value)}})});notice("主动消息设置已保存");await load()}catch(e){notice(e.message,true)}};
$("reload-history").onclick=()=>load().catch(e=>notice(e.message,true));
if(token){load().catch(()=>login())}else login();
