"use strict";
const $=id=>document.getElementById(id);
let bridge=null,state=null,currentPersona=null,currentProvider=null;
const pageNames={overview:"总览",persona:"人设工作台",providers:"模型接口",generate:"生图工作台",active:"主动消息",history:"生成历史"};
function text(id,value){$(id).textContent=value==null||value===""?"—":String(value)}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function notice(message,error=false){const n=$("notice");n.hidden=!message;n.textContent=message;n.className=`notice${error?" error":""}`}
async function request(path,options={}){if(!bridge)throw new Error("AstrBot 插件页面桥接尚未就绪");const clean=path.replace(/^\/+/,"");const result=options.method==="POST"?await bridge.apiPost(clean,options.body||{}):await bridge.apiGet(clean,options.params||{});if(result?.status==="error")throw new Error(result.message||"请求失败");return result?.status==="ok"&&Object.prototype.hasOwnProperty.call(result,"data")?result.data:result}
function setPage(page){document.querySelectorAll("[data-panel]").forEach(x=>x.hidden=x.dataset.panel!==page);document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));text("page-title",pageNames[page]||page)}
function fillPersona(p){currentPersona=p;["name","description","positive","negative","style"].forEach(key=>$("p-"+key).value=p[key==="name"?"name":key==="description"?"description":key==="positive"?"positive_prompt":key==="negative"?"negative_prompt":"style_prompt"]||"");const s=p.state||{};$("p-outfit").value=s.outfit||"";$("p-pose").value=s.pose||"";$("p-expression").value=s.expression||"";$("p-scene").value=s.scene||"";$("p-pool").value=(p.outfit_pool||[]).join("\n");renderPrompt(p)}
function renderPrompt(p){const s=p?.state||{};$("prompt-preview").textContent=`正面：${[p?.style_prompt,p?.positive_prompt,s.outfit,s.pose,s.expression,s.scene].filter(Boolean).join(", ")}\n\n负面：${p?.negative_prompt||""}`}
function rowButton(label,handler){const b=document.createElement("button");b.textContent=label;b.onclick=handler;return b}
function renderPersonas(items){const box=$("persona-list");box.replaceChildren();for(const p of items){const row=document.createElement("div");row.className=`list-row ${p.id===currentPersona?.id?"active":""}`;const name=document.createElement("span");name.textContent=p.name||p.id;const small=document.createElement("small");small.textContent=` ${p.id||""}`;name.append(small);row.append(name,rowButton("编辑",()=>fillPersona(p)));box.append(row)}}
function renderProviders(items){const box=$("provider-list");box.replaceChildren();for(const p of items){const row=document.createElement("div");row.className=`list-row ${p.name===currentProvider?.name?"active":""}`;const name=document.createElement("span");name.textContent=p.name||"default";const small=document.createElement("small");small.textContent=` ${p.kind||""} / ${p.model||"未配置模型"}`;name.append(small);row.append(name,rowButton("编辑",()=>fillProvider(p)));box.append(row)}}
function fillProvider(p){currentProvider=p;$("v-name").value=p.name||"";$("v-kind").value=p.kind||"openai";$("v-endpoint").value=p.endpoint||"";$("v-model").value=p.model||"";$("v-key").value="";$("v-header").value=p.auth_header||"Authorization";$("v-prefix").value=p.auth_prefix??"Bearer ";$("v-edit").checked=Boolean(p.supports_image_edit);$("v-negative").checked=p.negative_prompt!==false}
function renderTargets(items){const box=$("target-list");box.replaceChildren();if(!items.length){box.textContent="暂无目标。请先在 QQ 私聊中与机器人产生一次消息。";return}for(const t of items){const row=document.createElement("div");row.className="list-row";const label=document.createElement("span");label.textContent=t.sender_id||t.umo;const small=document.createElement("small");small.textContent=` ${t.enabled?"已启用":"已停用"} · 未回复 ${t.unanswered||0} 次`;label.append(small);const actions=document.createElement("span");actions.append(rowButton(t.enabled?"停用":"启用",()=>targetAction({action:"toggle",umo:t.umo})),rowButton("移除",()=>targetAction({action:"remove",umo:t.umo})));row.append(label,actions);box.append(row)}}
function renderHistory(items){const box=$("history-list");box.replaceChildren();if(!items.length){box.textContent="还没有生成记录。";return}for(const h of [...items].reverse()){const row=document.createElement("div");row.className="history-row";if(h.image){const image=document.createElement("img");image.src=h.image;image.alt="生成结果";row.append(image)}else row.append(document.createElement("div"));const body=document.createElement("div");const title=document.createElement("strong");title.textContent=h.caption||h.prompt||"未命名请求";const status=document.createElement("small");status.textContent=`${h.provider||""} · ${h.ok?"成功":"失败"}`;const error=document.createElement("p");error.textContent=h.error||"";body.append(title,status,error);const date=document.createElement("small");date.textContent=new Date((h.at||0)*1000).toLocaleString("zh-CN");row.append(body,date);box.append(row)}}
async function load(){const [data,personas,providers,targets,history]=await Promise.all([request("page/state"),request("page/personas"),request("page/providers"),request("page/targets"),request("page/history")]);state=data;renderOverview(data);renderPersonas(personas.items||[]);renderProviders(providers.items||[]);renderTargets(targets.items||[]);renderHistory(history.items||[]);if(!currentPersona&&personas.items?.length)fillPersona(personas.items[0]);if(!currentProvider&&providers.items?.length)fillProvider(providers.items[0]);await loadLlm();$("status-label").textContent="控制台已连接";$("status-dot").className="dot online"}
async function loadLlm(){const data=await request("page/llm/providers");const selected=data.selected||{};const providers=data.items||[];const ps=$("l-provider"),ms=$("l-model");ps.replaceChildren();providers.forEach(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=`${p.id} · ${p.type||""}`;ps.append(o)});if(selected.provider_id)ps.value=selected.provider_id;function models(){const p=providers.find(x=>x.id===ps.value);ms.replaceChildren();(p?.models||[]).forEach(m=>{const o=document.createElement("option");o.value=m;o.textContent=m;ms.append(o)});if(selected.model)ms.value=selected.model}ps.onchange=models;models();$("l-fallback").checked=selected.fallback_to_current!==false;$("l-timeout").value=selected.timeout_sec||45}
async function testLlm(){const result=await request("page/llm/test",{method:"POST",body:{provider_id:$("l-provider").value,model:$("l-model").value}});$("llm-test-result").textContent=result.ok?`成功 · ${result.provider_id} / ${result.model} · ${result.elapsed_ms} ms · ${result.text}`:`失败：${result.message||"未知错误"}`}
async function targetAction(body){try{await request("page/targets",{method:"POST",body});await load()}catch(e){notice(e.message,true)}}
async function submitGenerate(input,output){$(output).textContent="生成中…";try{const result=await request("page/generate",{method:"POST",body:input});$(output).replaceChildren();if(result.image){const p=document.createElement("p");p.textContent=result.caption||"生成完成";const img=document.createElement("img");img.src=result.image;img.alt="生成结果";$(output).append(p,img)}else $(output).textContent=result.message||"生成完成";await load()}catch(e){$(output).textContent=e.message;notice(e.message,true)}}
document.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>setPage(x.dataset.page));$("refresh").onclick=()=>load().catch(e=>notice(e.message,true));
$("quick-form").onsubmit=e=>{e.preventDefault();const prompt=$("quick-input").value.trim();if(prompt)submitGenerate({text:prompt},"quick-result")};
$("save-persona").onclick=async()=>{const p={...(currentPersona||{}),id:currentPersona?.id||`persona-${Date.now()}`,name:$("p-name").value,description:$("p-description").value,positive_prompt:$("p-positive").value,negative_prompt:$("p-negative").value,style_prompt:$("p-style").value,state:{outfit:$("p-outfit").value,pose:$("p-pose").value,expression:$("p-expression").value,scene:$("p-scene").value},outfit_pool:$("p-pool").value.split(/\r?\n/).filter(Boolean)};try{await request("page/personas",{method:"POST",body:p});notice("人设已保存");await load()}catch(e){notice(e.message,true)}};
$("new-persona").onclick=()=>fillPersona({id:`persona-${Date.now()}`,name:"新的人设",state:{},outfit_pool:[]});$("reset-state").onclick=()=>{if(currentPersona)fillPersona({...currentPersona,state:{}})};
$("save-provider").onclick=async()=>{const p={name:$("v-name").value,kind:$("v-kind").value,endpoint:$("v-endpoint").value,model:$("v-model").value,api_key:$("v-key").value,auth_header:$("v-header").value,auth_prefix:$("v-prefix").value,supports_image_edit:$("v-edit").checked,negative_prompt:$("v-negative").checked};try{await request("page/providers",{method:"POST",body:p});notice("模型接口已保存");await load()}catch(e){notice(e.message,true)}};
$("list-image-models").onclick=async()=>{try{const result=await request("page/image/models",{method:"POST",body:{name:$("v-name").value}});const select=$("v-model");select.replaceChildren();(result.models||[]).forEach(m=>{const o=document.createElement("option");o.value=m;o.textContent=m;select.append(o)});notice(`${result.models?.length||0} 个模型已获取${result.automatic===false?"（该接口不支持自动枚举）":""}`)}catch(e){notice(e.message,true)}};
$("test-image-connection").onclick=async()=>{try{const result=await request("page/image/test",{method:"POST",body:{name:$("v-name").value}});$("provider-test-result").textContent=result.ok?`连接成功 · ${result.elapsed_ms} ms`:`连接失败：${result.message||"未知错误"}`}catch(e){$("provider-test-result").textContent=e.message}};
$("test-image-generation").onclick=async()=>{try{const result=await request("page/image/test",{method:"POST",body:{name:$("v-name").value,generate_image:true}});$("provider-test-result").replaceChildren();if(result.ok){const p=document.createElement("p");p.textContent=`测试图生成成功 · ${result.elapsed_ms} ms`;const img=document.createElement("img");img.src=result.image;img.alt="测试图";$("provider-test-result").append(p,img)}else $("provider-test-result").textContent=`测试图失败：${result.message||"未知错误"}`}catch(e){$("provider-test-result").textContent=e.message}};
$("refresh-llm").onclick=()=>loadLlm().catch(e=>notice(e.message,true));$("test-llm").onclick=()=>testLlm().catch(e=>$("llm-test-result").textContent=`失败：${e.message}`);$("save-llm").onclick=async()=>{try{await request("page/llm/save",{method:"POST",body:{provider_id:$("l-provider").value,model:$("l-model").value,fallback_to_current:$("l-fallback").checked,timeout_sec:Number($("l-timeout").value)}});notice("LLM 设置已保存")}catch(e){notice(e.message,true)}};
$("new-provider").onclick=()=>fillProvider({name:`provider-${Date.now()}`,kind:"openai"});$("generate-button").onclick=()=>submitGenerate({text:$("g-prompt").value,mode:$("g-mode").value,provider:$("g-provider").value,width:Number($("g-width").value),height:Number($("g-height").value)},"generate-result");
$("save-active").onclick=async()=>{try{await request("page/settings",{method:"POST",body:{active:{enabled:$("a-enabled").checked,check_interval_sec:Number($("a-interval").value),min_gap_sec:Number($("a-gap").value),silence_after:Number($("a-silence").value)}}});notice("主动消息设置已保存");await load()}catch(e){notice(e.message,true)}};
$("reload-history").onclick=()=>load().catch(e=>notice(e.message,true));
(async()=>{try{bridge=window.AstrBotPluginPage;await bridge.ready();await load()}catch(e){notice(e.message||"插件页面桥接失败",true)}})();
